# test_optimizer_step

```python
   w = np.array([[1, 3, 0], [0, 1, -1]])
   x = (np.array([[1, -1, 2]])).T
   b = np.array([[-2, -3]]).T
   y_act = np.array([[1, 2]]).T
```
#### References 
* https://medium.com/coinmonks/create-a-neural-network-in-pytorch-and-make-your-life-simpler-ec5367895199 
* https://discuss.pytorch.org/t/how-to-manually-set-the-weights-in-a-two-layer-linear-model/45902

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np 
import torch.optim as optim 

In [2]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(3,2)  

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = self.fc1(x)
        return x


In [4]:
input = torch.FloatTensor([[1, -1, 2]])
net = Net() 
net.fc1.weight = nn.Parameter( torch.FloatTensor([[1, 3, 0], [0, 1, -1]]))
net.fc1.bias   = nn.Parameter(torch.FloatTensor([[-2, -3]]))

In [5]:
for param in net.fc1.parameters():
    print(param.data)

tensor([[ 1.,  3.,  0.],
        [ 0.,  1., -1.]])
tensor([[-2., -3.]])


In [6]:
output = net(input)
print(output)

tensor([[-4., -6.]], grad_fn=<AddmmBackward>)


In [27]:
w = np.array([[1, 3, 0], [0, 1, -1]])
x = (np.array([[1, -1, 2]])).T
b = np.array([[-2, -3]]).T
y_act = np.array([[1, 2]]).T

In [28]:
w@x+b

array([[-4],
       [-6]])

In [29]:
target = torch.FloatTensor([[1, 2]])
target = target.view(1, -1)

In [30]:
criteria = nn.MSELoss()
loss = criteria(output, target)
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)

In [31]:
print(loss)

tensor(44.5000, grad_fn=<MseLossBackward>)


In [11]:
(5*5+64)*.5

44.5

In [21]:

for epoch in range(50):
    # Forward Propagation
    y_pred = net(input)
    # Compute and print loss
    loss = criteria(y_pred, target)
    if epoch %10 ==0 :
        print('epoch: ', epoch,' loss: ', loss.item())
    # Zero the gradients
    optimizer.zero_grad()
    
    # perform a backward pass (backpropagation)
    loss.backward()
    
    # Update the parameters
    optimizer.step()
    
print('epoch: ', epoch,' loss: ', loss.item())

epoch:  0  loss:  0.0008333049481734633
epoch:  10  loss:  0.0001951882877619937
epoch:  20  loss:  4.5719396439380944e-05
epoch:  30  loss:  1.0709278285503387e-05
epoch:  40  loss:  2.5082044885493815e-06
epoch:  49  loss:  6.797947662562365e-07
