In [47]:
import numpy as np 
np.random.seed(100)

In [48]:
w=np.array([[1,2,1],[2,0,-1]])
print(w)
x=np.random.rand(3,5)
print("x=np."+repr(x)) 

[[ 1  2  1]
 [ 2  0 -1]]
x=np.array([[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
       [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
       [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749]])


In [49]:
w@x

array([[ 1.67786514,  1.82906968,  2.26155132,  1.2265662 ,  1.37460301],
       [ 0.19548793,  0.34753665,  0.66370696,  1.58117537, -0.21025978]])

In [46]:
y_pred=np.random.rand(2,5)
print("y_pre=np."+repr(y_pred))

y_pre=np.array([[0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375],
       [0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045]])


In [16]:
err_y = y_pred-w@x

In [17]:
err_y

array([[-2.90744166, -2.76690973, -1.09443327, -1.28127583, -0.92800047],
       [-0.75209635,  1.12543011,  0.55214063,  0.50130161, -0.22750847]])

In [18]:
(w@x)*err_y

array([[-9.53720444, -7.67152905, -1.47404798, -2.66113089, -0.87534149],
       [-1.01603683, -0.58705313, -0.24680296, -0.05983444, -0.06005872]])

In [22]:
delw=(w@x)*err_y

In [23]:
delw=delw.sum(axis=1)

In [40]:
delw=delw.reshape((-1, len(delw) ))
print("Shape of delw:{}. delw:{}".format(delw.shape, delw))

Shape of delw:(1, 2). delw:[[-22.21925386  -1.96978609]]


In [36]:
ones = np.ones((w.shape[1],1))
print(ones)

[[1.]
 [1.]
 [1.]]


In [38]:
ones@delw

array([[-22.21925386,  -1.96978609],
       [-22.21925386,  -1.96978609],
       [-22.21925386,  -1.96978609]])

In [51]:
print(w.size)

6
