In [1]:
import numpy as np 

In [3]:
from sklearn.datasets import fetch_openml

In [4]:
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)

In [17]:
img_1 = X[1,:]
print(img_1.shape)
img_1 = img_1.reshape(28,28)
print(img_1.shape)

(784,)
(28, 28)


In [15]:
a=np.array([1,2,3,4,5,6, 7,8,9])
b=a.reshape(-1,3)
print(a)
print(b)
print(b.shape)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [9]:
np.min(y)

'0'

In [11]:
int(np.max(y))+1

10

In [18]:
X.shape[1]

784

In [19]:
al=['abhijat','vatsyayan','50 union']
al.pop()

'50 union'

In [20]:
al

['abhijat', 'vatsyayan']

In [21]:
"_".join(al)

'abhijat_vatsyayan'

In [26]:
if 'x' in al[0]:
    print("yes")
else:
    print("no")

no
