In [2]:
import numpy as np 

In [3]:
import numpy as np
a=np.array([[1,2,3,4],[3,4,5,6],[-1,0,1,3]])
print(a)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [-1  0  1  3]]


In [4]:
def sig(x):
    return 1.0/(1+np.exp(-x))

In [53]:
y_p=np.array([[1,3,-1,0],[0,9,1,3]]).T
print(repr(y_p))

array([[ 1,  0],
       [ 3,  9],
       [-1,  1],
       [ 0,  3]])


In [58]:
def softmax(input):
    e = np.exp(input)
    s = np.sum(e, axis=0) 
    return e/s 

In [59]:
sx = softmax(y_p)
print(repr(sx))

array([[1.12457214e-01, 1.23048334e-04],
       [8.30952661e-01, 9.97070980e-01],
       [1.52194289e-02, 3.34480051e-04],
       [4.13706969e-02, 2.47149186e-03]])


In [8]:
print(repr(sx))

array([[0.11245721],
       [0.83095266],
       [0.01521943],
       [0.0413707 ]])


In [45]:
yt=np.array([[0,0,1,0],[1,0,0,0]]).T
print(repr(yt))

array([[0, 1],
       [0, 0],
       [1, 0],
       [0, 0]])


In [46]:
print(repr(yt>0))

array([[False,  True],
       [False, False],
       [ True, False],
       [False, False]])


In [47]:
print(repr(np.where(np.any(yt>0, axis=0))))

(array([0, 1], dtype=int64),)


In [48]:
i,j = np.nonzero(yt) 

In [49]:
print(i,j)

[0 2] [1 0]


In [50]:
(yt>0).argmax(axis=0)

array([2, 0], dtype=int64)

In [60]:
x=np.array([[1,-3,5,0],[0,3,-4,2.9, 0.0000000001]])
print(repr(x))

array([list([1, -3, 5, 0]), list([0, 3, -4, 2.9, 1e-10])], dtype=object)


In [61]:
x[x==0]= 0.00000001

In [62]:
print(repr(x))

array([list([1, -3, 5, 0]), list([0, 3, -4, 2.9, 1e-10])], dtype=object)
