In [ ]:
import numpy as np 
a=np.array([[1,2,1],[-1,0,2]])
print(a)
x=np.array([[2,-1]]).T
print(x)

In [ ]:
a*x

In [ ]:
ones = np.ones((3,5))
print(ones)

In [ ]:
r = np.random.rand(ones.size).reshape(ones.shape)

In [ ]:
print(a)
np.average(a, axis=1).reshape(2,1)

In [ ]:
x=None 
value = x and ones 
if value : 
    print("value  ..")
else:
    print('Not inited')

In [ ]:
x=np.random.rand(3,5)
print(x)
w = np.array([[1, 3, -1], [0, -4, 2]])
b = np.array([[-3,2]]).reshape((w.shape[0],1))
y = w@x + b 
print(y)

In [ ]:
m,n=20,30 
k=2
end_i = m-k
end_j = n-k
for i in range(end_i):
    for j in range(end_j):
        i_idx = (i, i+k)
        j_idx = (j, j+k)
        print("[{}][{}]".format(i_idx, j_idx))

In [2]:
import numpy as np
a=np.array([[1,2,3,4],[3,4,5,6],[-1,0,1,3]])

In [3]:
print(a)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [-1  0  1  3]]


In [4]:
w=np.array([[-10,-12],[-9,-15]])

In [6]:
print(repr(w))
print(repr(a))

array([[-10, -12],
       [ -9, -15]])
array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [-1,  0,  1,  3]])


In [14]:
ranges=((1:3),(2:4))
a[ranges[0],ranges[1]]+=w

SyntaxError: invalid syntax (<ipython-input-14-a1504144563c>, line 1)

In [12]:
print(repr(a))

array([[  1,   2,   3,   4],
       [  3,   4,  -5,  -6],
       [ -1,   0,  -8, -12]])


In [22]:
k=2
i=1
x_idx=[x for x in range(i-1, i+k)]
print(x_idx)
j=2
y_idx=[x for x in range(j-1,j+k)]
print(y_idx)

[0, 1, 2]
[1, 2, 3]


In [24]:
print(np.argmax(a))

3


In [30]:
a[1][2]

-5

In [28]:
k=3 
i_start=4

for i in range(i_start,i_start+k):
    print(i) 

4
5
6
