In [1]:
import numpy as np 
a=np.array([[1,2,1],[-1,0,2]])
print(a)
x=np.array([[2,-1]]).T
print(x)

[[ 1  2  1]
 [-1  0  2]]
[[ 2]
 [-1]]


In [2]:
a*x

array([[ 2,  4,  2],
       [ 1,  0, -2]])

In [3]:
ones = np.ones((3,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
r = np.random.rand(ones.size).reshape(ones.shape)

In [11]:
print(a)
np.average(a, axis=1).reshape(2,1)

[[ 1  2  1]
 [-1  0  2]]


array([[1.33333333],
       [0.33333333]])

In [15]:
x=None 
value = x and ones 
if value : 
    print("value  ..")
else:
    print('Not inited')

None
Not inited


In [22]:
x=np.random.rand(3,5)
print(x)
w = np.array([[1, 3, -1], [0, -4, 2]])
b = np.array([[-3,2]]).reshape((w.shape[0],1))
y = w@x + b 
print(y)

[[0.27324892 0.20794064 0.40709614 0.57989882 0.66002588]
 [0.40336112 0.00177118 0.09311274 0.07630574 0.41911615]
 [0.37670757 0.49653544 0.46344111 0.57995388 0.43835633]]
[[-1.89337527 -3.28328124 -2.77700675 -2.77113786 -1.520982  ]
 [ 1.13997064  2.98598614  2.55443125  2.85468483  1.20024805]]
