In [2]:
import numpy as np 

In [3]:
from sklearn.datasets import fetch_openml

In [4]:
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)

In [17]:
img_1 = X[1,:]
print(img_1.shape)
img_1 = img_1.reshape(28,28)
print(img_1.shape)

(784,)
(28, 28)


In [15]:
a=np.array([1,2,3,4,5,6, 7,8,9])
b=a.reshape(-1,3)
print(a)
print(b)
print(b.shape)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [9]:
np.min(y)

'0'

In [11]:
int(np.max(y))+1

10

In [18]:
X.shape[1]

784

In [19]:
al=['abhijat','vatsyayan','50 union']
al.pop()

'50 union'

In [20]:
al

['abhijat', 'vatsyayan']

In [21]:
"_".join(al)

'abhijat_vatsyayan'

In [26]:
if 'x' in al[0]:
    print("yes")
else:
    print("no")

no


In [33]:
a=np.array([[1,-1,2],[9,0,-3]])
print(a)

[[ 1 -1  2]
 [ 9  0 -3]]


In [31]:
b=np.ones_like(a)
print(b)
b = b*(a>0)
print(b)

[[1 1 1]
 [1 1 1]]
[[1 0 1]
 [1 0 0]]


In [37]:
a_sq = np.square(a)
print(a_sq)
sums = np.sum(a_sq, axis=0)
print(sums)
a_norm = a/sums 
print(a_norm)

[[ 1  1  4]
 [81  0  9]]
[82  1 13]
[[ 0.01219512 -1.          0.15384615]
 [ 0.1097561   0.         -0.23076923]]


In [38]:
9/82

0.10975609756097561

In [39]:
np.exp(-7176278)

0.0

In [40]:
print(a)

[[ 1 -1  2]
 [ 9  0 -3]]


In [44]:
mu=np.mean(a, axis=1).reshape(a.shape[0],1)
print(mu.shape)

(2, 1)


In [7]:
b=np.array([[.1,.3,-.9],[2,-9,1]]).T
print(b) 

[[ 0.1  2. ]
 [ 0.3 -9. ]
 [-0.9  1. ]]


In [19]:
p=.5
for i in range(20):
    row =[np.random.binomial(1, p) for _ in range(20)]
    m = np.mean(row) 
    print("{} , mean={}".format(row, m))

[0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0] , mean=0.5
[1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1] , mean=0.6
[0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1] , mean=0.45
[0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0] , mean=0.6
[0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0] , mean=0.55
[1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1] , mean=0.5
[0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0] , mean=0.45
[0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0] , mean=0.3
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1] , mean=0.35
[1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0] , mean=0.35
[1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1] , mean=0.55
[0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0] , mean=0.5
[1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0] , mean=0.45
[0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,

In [25]:
print(b) 
dp = np.array([[np.random.binomial(1,p) for _ in range(3)]]).
print(dp) 
print(b*dp)

[[ 0.1  2. ]
 [ 0.3 -9. ]
 [-0.9  1. ]]
[[1]
 [0]
 [0]]
[[ 0.1  2. ]
 [ 0.  -0. ]
 [-0.   0. ]]
