In [3]:
import numpy as np 

In [2]:
a=np.array([[1,2,3,4],[3,4,5,6],[-1,0,1,3]])
print(a)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [-1  0  1  3]]


In [4]:
def sig(x):
    return 1.0/(1+np.exp(-x))

In [53]:
y_p=np.array([[1,3,-1,0],[0,9,1,3]]).T
print(repr(y_p))

array([[ 1,  0],
       [ 3,  9],
       [-1,  1],
       [ 0,  3]])


In [58]:
def softmax(input):
    e = np.exp(input)
    s = np.sum(e, axis=0) 
    return e/s 

In [59]:
sx = softmax(y_p)
print(repr(sx))

array([[1.12457214e-01, 1.23048334e-04],
       [8.30952661e-01, 9.97070980e-01],
       [1.52194289e-02, 3.34480051e-04],
       [4.13706969e-02, 2.47149186e-03]])


In [8]:
print(repr(sx))

array([[0.11245721],
       [0.83095266],
       [0.01521943],
       [0.0413707 ]])


In [45]:
yt=np.array([[0,0,1,0],[1,0,0,0]]).T
print(repr(yt))

array([[0, 1],
       [0, 0],
       [1, 0],
       [0, 0]])


In [46]:
print(repr(yt>0))

array([[False,  True],
       [False, False],
       [ True, False],
       [False, False]])


In [47]:
print(repr(np.where(np.any(yt>0, axis=0))))

(array([0, 1], dtype=int64),)


In [48]:
i,j = np.nonzero(yt) 

In [49]:
print(i,j)

[0 2] [1 0]


In [50]:
(yt>0).argmax(axis=0)

array([2, 0], dtype=int64)

In [60]:
x=np.array([[1,-3,5,0],[0,3,-4,2.9, 0.0000000001]])
print(repr(x))

array([list([1, -3, 5, 0]), list([0, 3, -4, 2.9, 1e-10])], dtype=object)


In [61]:
x[x==0]= 0.00000001

In [62]:
print(repr(x))

array([list([1, -3, 5, 0]), list([0, 3, -4, 2.9, 1e-10])], dtype=object)


In [3]:
yt=np.array([0,2])

In [10]:
print(yt)
print(a)
a[yt]

[0 2]
[[ 1  2  3  4]
 [ 3  4  5  6]
 [-1  0  1  3]]


array([[ 1,  2,  3,  4],
       [-1,  0,  1,  3]])

In [22]:
train=np.random.choice(range(30), 20, replace=False)
print(len(train))
full=set(range(30))
print(full-set(train))

print(train)

20
{1, 2, 8, 12, 16, 17, 20, 21, 25, 28}
[23  3 19 10 27 14 26  0  6  7 18  5  4 22 29 13 24  9 15 11]


In [11]:
w = np.array([[1, 3, -1], [0, -4, 2]])
b = np.array([[1, 2]]).reshape((w.shape[0], 1))
x=np.array([[1,2,4],[.4,.5,.8],[3,4,0]]).T
y=w@x+b
print(repr(y))

array([[  4. ,   2.1,  16. ],
       [  2. ,   1.6, -14. ]])


In [14]:
y@x.T/y.shape[1]

array([[ 17.61333333,  24.35      ,   5.89333333],
       [-13.12      , -17.06666667,   3.09333333]])

In [16]:
np.average(y, axis=1).reshape(-1,1)

array([[ 7.36666667],
       [-3.46666667]])

In [19]:
w.T@y

array([[ 4.00e+00,  2.10e+00,  1.60e+01],
       [ 4.00e+00, -1.00e-01,  1.04e+02],
       [ 0.00e+00,  1.10e+00, -4.40e+01]])

In [21]:
x=np.array([[1,2,4]]).T

In [22]:
y=w@x+b
print("--- y ---")
print(y) 
print("--- y@x.T")
print(y@x.T)
print("--- w.T@y")
print(w.T@y)

--- y ---
[[4]
 [2]]
--- y@x.T
[[ 4  8 16]
 [ 2  4  8]]
--- w.T@y
[[4]
 [4]
 [0]]


In [26]:
np.power(2,10)

1024

In [40]:
a=np.random.rand(3,3,2)
print(a)
print("-------------------")
b = np.array([[1,-1,1],[0,0,1],[1,0,0]]).reshape(3,3,1)
print("B -----------")
print(b) 
print("a*b --------------")
print(a*b)
c=a*b
print("--------------------------------------")
print("--------------A[:,:,0] ---------------")
print(a[:,:,0])
print("--------------------------------------")
print("--------------b[:,:,0] ---------------")
print(b[:,:,0])
print("--------------------------------------")
print("--------------c[:,:,0] ---------------")
print(c[:,:,0])


[[[0.4497591  0.89818251]
  [0.78391262 0.96498873]
  [0.58190934 0.1667085 ]]

 [[0.40008163 0.48082138]
  [0.12866614 0.2912605 ]
  [0.23851323 0.62142716]]

 [[0.82959211 0.97989429]
  [0.70430402 0.24843739]
  [0.03746294 0.29855781]]]
-------------------
B -----------
[[[ 1]
  [-1]
  [ 1]]

 [[ 0]
  [ 0]
  [ 1]]

 [[ 1]
  [ 0]
  [ 0]]]
a*b --------------
[[[ 0.4497591   0.89818251]
  [-0.78391262 -0.96498873]
  [ 0.58190934  0.1667085 ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]
  [ 0.23851323  0.62142716]]

 [[ 0.82959211  0.97989429]
  [ 0.          0.        ]
  [ 0.          0.        ]]]
--------------------------------------
--------------A[:,:,0] ---------------
[[0.4497591  0.78391262 0.58190934]
 [0.40008163 0.12866614 0.23851323]
 [0.82959211 0.70430402 0.03746294]]
--------------------------------------
--------------b[:,:,0] ---------------
[[ 1 -1  1]
 [ 0  0  1]
 [ 1  0  0]]
--------------------------------------
--------------c[:,:,0] ---------------


In [46]:
b=np.array([[1,0,-1],[2,1,4],[5,5,5]])
print(b)
np.average(b, axis=1)

[[ 1  0 -1]
 [ 2  1  4]
 [ 5  5  5]]


array([0.        , 2.33333333, 5.        ])

In [53]:
yp=np.array([[  5.,   7.],
       [ -8., -14.]])
yt=np.array([[-1.,  1.],
       [-3., -1.]]).T
err=np.sum(np.square(yp-yt))/yp.size
print(err)

96.5


In [51]:
w=np.array([[ 1.,  3., -1.],
       [ 0., -4.,  2.]])
b=np.array([[-3.],
       [ 2.]])
x = np.array([[1, -1], [2, 3], [-1, -2]], dtype=np.float)

In [52]:
y=w@x+b
print(y) 

[[  5.   7.]
 [ -8. -14.]]


In [42]:
w = np.array([[1, 3, -1], [0, -4, 2]])
b = np.array([[-3, 2]]).T
x = np.array([[1], [2], [-1]])
def y(x):
    return w@x + b

In [43]:
print("------ W ---------")
print(w)
print("------ B ---------")
print(b)
print("------ X ----------")
print(x) 
print("------------------")
yp=y(x)
print(yp)

------ W ---------
[[ 1  3 -1]
 [ 0 -4  2]]
------ B ---------
[[-3]
 [ 2]]
------ X ----------
[[ 1]
 [ 2]
 [-1]]
------------------
[[ 5]
 [-8]]


In [45]:
x@yp.T

array([[  5,  -8],
       [ 10, -16],
       [ -5,   8]])

In [13]:
g=np.average(yp, axis=1)
print(g) 

[  8.5 -13.5]


In [15]:
x@g

array([ 22. , -23.5,  18.5])