## Pytorch gradient calculation example 
Keeping this code around as pytorch reference for a really simple piece of code 
to caculate gradients across a layer. Useful for comparing with autodiff.light code 

**Uses np by design - it is easier to copy correctly and run in numpy based code**

In [1]:
import torch
import torch.nn as nn
import torch.autograd 
import numpy as np

In [3]:
dense = nn.Linear(3,2)
model_w = np.array([[1, 3, -1], [0, -4, 2]])
model_b = np.array([-3, 2])
w_tensor = torch.from_numpy(model_w).float()
b_tensor = torch.from_numpy(model_b).float() 
w = nn.Parameter(w_tensor)
b = nn.Parameter(b_tensor)
dense.weight  = w 
dense.bias = b

In [4]:
x = np.array([[1, -1], [2, 3.], [-1, -2.]]).T
input = torch.tensor([[1, -1], [2, 3.], [-1, -2.]], requires_grad=True).T
output = dense(input) 
output.backward(torch.ones_like(output))

In [6]:
print("---------------------------------")
print("-----  Input transpose ----------")
print(x.T) 
print("----------- Output --------------")
print(output)
print("-------- Weight gradient --------")
print(dense.weight.grad)
print("-------- Bias gradient ----------")
print(dense.bias.grad)

---------------------------------
-----  Input transpose ----------
[[ 1. -1.]
 [ 2.  3.]
 [-1. -2.]]
----------- Output --------------
tensor([[  5.,  -8.],
        [  7., -14.]], grad_fn=<AddmmBackward>)
-------- Weight gradient --------
tensor([[ 0.,  5., -3.],
        [ 0.,  5., -3.]])
-------- Bias gradient ----------
tensor([2., 2.])
