In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np 
import torch.optim as optim 
import sys 
import os 
import matplotlib.pyplot as plt

In [2]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv =  nn.Conv2d(1,1,kernel_size=(2,2))

    def forward(self, x):
        return self.conv(x) 

In [3]:
net = Net() 
kernel = nn.Parameter( torch.FloatTensor([[[[1, -1], [0, 2]]]]))
print(kernel.data.shape)
net.conv.weight = kernel 
print(net.conv.bias.shape)
bias = nn.Parameter(torch.FloatTensor([0]))
net.conv.bias = bias 

torch.Size([1, 1, 2, 2])
torch.Size([1])


In [4]:
img = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [-1, 0, 1, 3], [0, 2, -1, 4]])
input = torch.from_numpy(img).view(1,1,4,4).float()
print(input.shape)
output = net(input)

torch.Size([1, 1, 4, 4])


In [5]:
print("Output --- ")
print(output.data)
print("\nKernel ---")
print(net.conv.weight.data)
print("\nBias ---")
print(net.conv.bias.data)

Output --- 
tensor([[[[ 7.,  9., 11.],
          [-1.,  1.,  5.],
          [ 3., -3.,  6.]]]])

Kernel ---
tensor([[[[ 1., -1.],
          [ 0.,  2.]]]])

Bias ---
tensor([0.])


In [6]:
grad_back = np.ones_like(output.data)
target = torch.from_numpy(grad_back) 
criteria = nn.MSELoss()
loss = criteria(output, target)
optimizer = torch.optim.SGD(net.parameters(), lr=.001)

In [7]:
optimizer.zero_grad()
    
# perform a backward pass (backpropagation)
loss.backward()
    
# Update the parameters
optimizer.step()

In [20]:
print(net.conv.weight.data)
print(net.conv.weight.grad)
print("Now printing the bias after gradient descent step")
print(net.conv.bias)
print(net.conv.bias.grad)

tensor([[[[ 0.9847, -1.0229],
          [-0.0207,  1.9636]]]])
tensor([[[[15.3333, 22.8889],
          [20.6667, 36.4444]]]])
Now printing the bias after gradient descent step
Parameter containing:
tensor([-0.0064], requires_grad=True)
tensor([6.4444])


In [10]:
print(grad_back)

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


In [14]:
print("Bias gradient:{}".format(net.conv.bias.grad))
print("Bias after update:{}".format(net.conv.bias.data))

Bias gradient:tensor([6.4444])
Bias after update:tensor([-0.0064])


In [12]:
6.44/9

0.7155555555555556

In [13]:
9/6.44

1.3975155279503104

In [18]:
def key_generator(i, j):
    return (i<<)

386547056640

In [21]:
58/9

6.444444444444445

In [22]:
np.sum(img) 

36

In [23]:
img.size

16