In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np 
import torch.optim as optim 
import sys 
import os 
import matplotlib.pyplot as plt

In [2]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.dense =  nn.Linear(3,2)

    def forward(self, x):
        return self.dense(x) 

In [3]:
net = Net() 
print("Printing dense layer weights...")
print(net.dense.weight.data)
print(net.dense.bias.data)
print("finished printing dense layer weights")
model_w = np.array([[1, 3, -1], [0, -4, 2]])
model_b = np.array([-3, 2])
w_tensor = torch.from_numpy(model_w).float()
b_tensor = torch.from_numpy(model_b).float() 
w = nn.Parameter(w_tensor)
b = nn.Parameter(b_tensor)
net.dense.weight  = w 
net.dense.bias = b
x = np.array([[1, -1], [2, 3], [-1, -2]]).T
print("------ ")
print("model_w=np.{}".format(repr(model_w)))
print("------ ")
print("x=np.{}".format(repr(x)))
print("----->>")
print("b=np.{}".format(repr(model_b)))
yy = x@model_w.T + model_b 
print("---- expected final value (directly computed)----")
print(repr(yy))
print(net.dense.bias.data)

Printing dense layer weights...
tensor([[ 0.3501,  0.5441, -0.5003],
        [-0.2972,  0.4666, -0.1532]])
tensor([0.2086, 0.3761])
finished printing dense layer weights
------ 
model_w=np.array([[ 1,  3, -1],
       [ 0, -4,  2]])
------ 
x=np.array([[ 1,  2, -1],
       [-1,  3, -2]])
----->>
b=np.array([-3,  2])
---- expected final value (directly computed)----
array([[  5,  -8],
       [  7, -14]])
tensor([-3.,  2.])


In [8]:
input = torch.from_numpy(x).float() 
print("Input Shape:{}".format(input.shape))
output = net(input)
print("Output:{}".format(output.data))
y = np.array([[-1, 1], [-3, -1]]).T
target = torch.from_numpy(y).float()
print("Printing target  >>>>")
print(target.data)

Input Shape:torch.Size([2, 3])
Output:tensor([[  5.,  -8.],
        [  7., -14.]])
Printing target  >>>>
tensor([[-1., -3.],
        [ 1., -1.]])


In [9]:
criteria = nn.MSELoss()
loss = criteria(output, target)
print("loss: {}".format(loss))
optimizer = torch.optim.SGD(net.parameters(), lr=.001)

loss: 66.5


In [10]:
optimizer.zero_grad()
# perform a backward pass (backpropagation)
loss.backward()
# Update the parameters
optimizer.step()

In [16]:
print("Printing the wight and weight gradient after one step")
print("Weight:{}".format(net.dense.weight.data))
print("W Grad:{}".format(net.dense.weight.grad.data))
print("\nPrinting bias and bias gradient after one step")
print("Bias:{}".format(net.dense.bias.data))
print("B grad:{}".format(net.dense.bias.grad.data))

Printing the wight and weight gradient after one step
Weight:tensor([[ 1.0000,  2.9850, -0.9910],
        [-0.0040, -3.9755,  1.9845]])
W Grad:tensor([[  0.0000,  15.0000,  -9.0000],
        [  4.0000, -24.5000,  15.5000]])

Printing bias and bias gradient after one step
Bias:tensor([-3.0060,  2.0090])
B grad:tensor([ 6., -9.])


In [ ]:
print(grad_back)

In [ ]:
print("Bias gradient:{}".format(net.conv.bias.grad))
print("Bias after update:{}".format(net.conv.bias.data))

In [ ]:
W=np.array([[ 1,  3, -1],
       [ 0, -4,  2]])
B=np.array([[-3],
       [ 2]])
X=np.array([[ 1, -1],
       [ 2,  3],
       [-1, -2]])

In [ ]:
W@X+B

In [ ]:
X.T@W.T + B.T

In [ ]:
F.linear(input, w, b)