In [1]:
import torch
import torch.nn as nn
import numpy as np 

In [24]:
cross_entropy = nn.CrossEntropyLoss(reduction='sum')
predicted =  torch.tensor([[1, 3, -1, 0], [0, 9, 1, 3.]], requires_grad=True )
#predicted =  torch.tensor([[1, 3, -1., 0]], requires_grad=True )
target = torch.tensor([1,3])
#target = torch.tensor([1])
print(target)
output = cross_entropy(predicted, target)
print("Cross entropy loss:{}".format(output))
print(predicted)

tensor([1, 3])
Cross entropy loss:6.18811559677124
tensor([[ 1.,  3., -1.,  0.],
        [ 0.,  9.,  1.,  3.]], requires_grad=True)


In [21]:
output.backward()

In [22]:
predicted.grad

tensor([[ 1.1246e-01, -1.6905e-01,  1.5219e-02,  4.1371e-02],
        [ 1.2305e-04,  9.9707e-01,  3.3448e-04, -9.9753e-01]])

In [ ]:
predicted = np.array([1, 3, -1, 0]).reshape(-1,1)
def softmax(predicted):
    numerator = np.exp(predicted)
    denominator=np.sum(numerator)
    return numerator/denominator 

In [ ]:
soft=softmax(predicted)
soft

In [ ]:
target = np.array([0,0,1,0]).reshape(-1,1)
def x_entropy(soft_probs, target):
    logs = np.log(soft_probs)
    return logs - target
x_ent = x_entropy(soft, target)

In [ ]:
x_ent 

In [ ]:
probs=np.array([.2,.3,.5]).reshape(3,1)
target=np.array([0,1,0]).reshape(3,1)
x_ent = x_entropy(probs, target)
x_ent 

In [11]:
a=np.array([[ 0.1125, -0.1690,  0.0152,  0.0414]]).reshape(-1)
b=np.array([[ 0.02287807],
       [-0.69561738],
       [ 0.12011585],
       [ 0.09396459]]).reshape(-1)
print(a)
print(b)

[ 0.1125 -0.169   0.0152  0.0414]
[ 0.02287807 -0.69561738  0.12011585  0.09396459]


In [12]:
a/b

array([4.91737284, 0.24294965, 0.1265445 , 0.4405915 ])

In [17]:
c=np.array([a,b])
c

array([[ 0.1125    , -0.169     ,  0.0152    ,  0.0414    ],
       [ 0.02287807, -0.69561738,  0.12011585,  0.09396459]])

In [18]:
np.max(c, axis=0)

array([ 0.1125    , -0.169     ,  0.12011585,  0.09396459])

In [19]:
c-np.max(c, axis=0)

array([[ 0.        ,  0.        , -0.10491585, -0.05256459],
       [-0.08962193, -0.52661738,  0.        ,  0.        ]])

In [23]:
predicted = np.array([[1, 3, -1, 0], [0, 9, 1, 3.]]).reshape(-1,2)
predicted

array([[ 1.,  3.],
       [-1.,  0.],
       [ 0.,  9.],
       [ 1.,  3.]])