In [24]:
import torch
import torch.nn as nn
import torch.autograd 
import numpy as np

In [20]:
x =  torch.tensor([[1, 2, 3], [3, 4, 1.]], requires_grad=True ).T
batch_norm = nn.BatchNorm1d(x.shape[1] )
y = batch_norm.forward(x) 
print(batch_norm.weight)

Parameter containing:
tensor([1., 1.], requires_grad=True)


In [21]:
torch.autograd.backward(y, grad_tensors=torch.ones_like(y)) 

In [23]:
print(batch_norm.weight.grad)
print(batch_norm.bias.grad)

tensor([ 0.0000e+00, -1.9116e-07])
tensor([3., 3.])


In [9]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.layer =  nn.BatchNorm1d(2)

    def forward(self, x):
        return self.layer(x) 
net = Net() 

In [10]:
y = net(x) 
print(y) 

tensor([[-1.2247,  0.2673],
        [ 0.0000,  1.0690],
        [ 1.2247, -1.3363]], grad_fn=<NativeBatchNormBackward>)


In [11]:
y.backward(torch.ones_like(y))

In [13]:
print(x.grad)

AttributeError: 'NoneType' object has no attribute 'data'

In [25]:
dense = nn.Linear(3,2)
model_w = np.array([[1, 3, -1], [0, -4, 2]])
model_b = np.array([-3, 2])
w_tensor = torch.from_numpy(model_w).float()
b_tensor = torch.from_numpy(model_b).float() 
w = nn.Parameter(w_tensor)
b = nn.Parameter(b_tensor)
dense.weight  = w 
dense.bias = b

In [27]:
x = np.array([[1, -1], [2, 3.], [-1, -2.]]).T
input = torch.tensor([[1, -1], [2, 3.], [-1, -2.]], requires_grad=True).T

In [33]:
output = dense(input) 


In [34]:
output.backward(torch.ones_like(output))

In [36]:
dense.weight.grad

tensor([[ 0.,  5., -3.],
        [ 0.,  5., -3.]])

In [38]:
dense.bias.grad 

tensor([2., 2.])

In [39]:
dense.bias

Parameter containing:
tensor([-3.,  2.], requires_grad=True)

In [40]:
print(output)

tensor([[  5.,  -8.],
        [  7., -14.]], grad_fn=<AddmmBackward>)
