In [11]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.layer =  nn.Sigmoid()

    def forward(self, x):
        return self.layer(x) 
net = Net()  
x = torch.tensor([[1, 2, 3, 4], [3, 4, 5, 6], [-1, 0, 1, 3.0]], requires_grad=True )

In [3]:
x = nn.Parameter(x) 
y=net(x)
print(y.data)

tensor([[0.7311, 0.8808, 0.9526, 0.9820],
        [0.9526, 0.9820, 0.9933, 0.9975],
        [0.2689, 0.5000, 0.7311, 0.9526]])


In [4]:
target = torch.zeros_like(y) 
loss_function = nn.MSELoss() 
loss = loss_function(y, target)
optimizer = torch.optim.SGD([x], lr=.001)

In [5]:
optimizer.zero_grad()
loss.backward()
optimizer.step()

In [6]:
torch.set_printoptions(precision=8, sci_mode=False)
print(loss)
print(x.grad) 

tensor(0.73330349, grad_fn=<MseLossBackward>)
tensor([[0.02395581, 0.01541301, 0.00717235, 0.00289084],
        [0.00717235, 0.00289084, 0.00110059, 0.00041006],
        [0.00881285, 0.02083333, 0.02395581, 0.00717235]])


In [13]:
a=np.array([[1, 2, 3, 4], [3, 4, 5, 6], [-1, 0, 1, 3.0]])
def sig(matrix):
    return 1 / (1 + np.exp(-matrix))

def loss(pred, target, use_av):
    del_y = pred-target
    value = np.sum(np.square(del_y))
    if use_av:
        value = value/pred.size
    return value 
def loss_grad(pred, target, use_av):
    value = 2*(pred-target)
    if use_av:
        value = 
    
a_sig = sig(a) 
print(repr(a_sig))

array([[0.73105858, 0.88079708, 0.95257413, 0.98201379],
       [0.95257413, 0.98201379, 0.99330715, 0.99752738],
       [0.26894142, 0.5       , 0.73105858, 0.95257413]])


[[ 9.9997604e-01  1.9999846e+00  2.9999928e+00  3.9999971e+00]
 [ 2.9999928e+00  3.9999971e+00  4.9999990e+00  5.9999995e+00]
 [-1.0000088e+00 -2.0833335e-05  9.9997604e-01  2.9999928e+00]]
